markdown: rdiscount 
permalink: /:year/:month/:title 
title: ÁõË¼†´@±´¼ªËþÐÐÐÇ
url: http://bjt.name
subscribe: http://bjt.name/feed.xml
exclude: [ README.md, newpost.rb ]
domain: www.bjt.name
author: bjt
email: sunbjt@gmail.com
auto: true
twitterID: sunbjt
duoshuoShortname: sunbjt